package org.project.portfolio.config

import io.swagger.v3.oas.models.Components
import io.swagger.v3.oas.models.OpenAPI
import io.swagger.v3.oas.models.info.Contact
import io.swagger.v3.oas.models.info.Info
import io.swagger.v3.oas.models.security.SecurityScheme
import org.springframework.boot.info.GitProperties
import org.springframework.context.annotation.Bean
import org.springframework.stereotype.Component
import java.time.Instant

/** Swagger 설정 */
@Component
class SwaggerConfig(
    private val gitProperties: GitProperties,
) {
    @Bean
    fun openAPI(): OpenAPI {
        return OpenAPI().components(
            Components().apply {
                securitySchemes(
                    mapOf(
                        BEARER_AUTH to securityScheme(),
                    ),
                )
            },
        ).info(info())
    }

    /**
     * Bearer Auth Security Scheme
     */
    private fun securityScheme(): SecurityScheme {
        return SecurityScheme()
            .type(io.swagger.v3.oas.models.security.SecurityScheme.Type.HTTP)
            .description(
                """<h3>Bearer Auth</h3>
                <p>JWT Token을 발급받아 Header에 넣어 요청합니다.</p>
                <p>Bearer [JWT Token 값]</p>
                """.trimIndent(),
            )
            .scheme("bearer")
            .bearerFormat("JWT")
    }

    /**
     * OpenAPI Info
     */
    private fun info(): Info {
        return Info().apply {
            title = "Portfolio Article API"
            description = """<h2>Article API</h2>
                <p>You can See Full Source Code at <a target="_blank" href="${gitProperties.get("remote.origin.url")}">Github</a></p>
                <p>API Document is generated by Swagger</p>
                |<h4>Last Commit Information</h4>
                |<p><strong>Message:</strong> ${gitProperties.get("commit.message.full")}</p>
                |<p><strong>Commit ID:</strong> ${gitProperties.get("commit.id")}</p>
                |<p><strong>Commit Time:</strong> ${Instant.ofEpochMilli(gitProperties.get("commit.time").toLong())}</p>
                |<p><strong>Committed by:</strong> ${gitProperties.get("commit.user.name")} (${gitProperties.get("commit.user.email")})</p>
                """.trimMargin()
            termsOfService = ""
            contact = Contact().apply {
                name = "Namju Kim"
                email = "cmsong111@gmail.com"
            }
            version = gitProperties.get("build.version")
        }
    }

    companion object {
        // Auth 방식
        const val BEARER_AUTH: String = "Bearer Authentication"
    }
}
