version: "3.0"

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: article
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"

  redis:
    image: redis:7.4-rc2-alpine
    restart: always
    ports:
      - "6379:6379"

  object-storage:
    image: bitnami/minio
    restart: always
    environment:
      MINIO_ROOT_USER: username
      MINIO_ROOT_PASSWORD: password
      MINIO_REGION_NAME: kr-busan-1
      MINIO_DEFAULT_BUCKET: "article:public"
    ports:
      - "9000:9000"
      - "9001:9001"
