spring:
  datasource:
    url: jdbc:mariadb://localhost/article
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        use_sql_comments: true
        highlight: true
        dialect: org.hibernate.dialect.MariaDBDialect

    defer-datasource-initialization: true

  data:
    redis:
      host: localhost
      port: 6379


  sql:
    init:
      mode: always

jwt:
  secret-key: ${JWT_SECRET:dGhpcy1pcy1zZWNyZXQta2V5LXJlcGxhY2Utd2l0aC15b3VyLW93bi1zZWNyZXQta2V5} # this-is-secret-key-replace-with-your-own-secret-key with BASE64 encoded
  expiration: 1800000 # 30 minutes

minio:
  url: http://localhost:9000
  access-key: username
  secret-key: password

springdoc:
  swagger-ui:
    tags-sorter: alpha

server:
  servlet:
    encoding:
      force-response: true # 한글 인코딩 반환 강제화
