spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: ${DATABASE_DRIVER:org.mariadb.jdbc.Driver}

  jpa:
    hibernate:
      ddl-auto: update

  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE}
      username: ${REDIS_USERNAME}
      password: ${REDIS_PASSWORD}

management:
  server:
    port: 8081

server:
  forward-headers-strategy: framework

logstash:
  host: ${LOGSTASH_HOST:localhost}
  port: ${LOGSTASH_PORT:5044}
