spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/article
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
