spring:
  application:
    name: portfolio

  profiles:
    default: local

  data:
    redis:
      host: localhost
      port: 6379
      database: 2

  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

  cloud:
    aws:
      s3:
        enabled: false

jwt:
  secret: ${JWT_SECRET:this-is-a-secret-key-and-it-should-be-kept-secure}
  issuer: ${JWT_ISSUER:localhost}
  access-expiry: ${JWT_ACCESS_EXPIRATION:3600}
  refresh-expiry: ${JWT_REFRESH_EXPIRATION:604800}


springdoc:
  swagger-ui:
    tags-sorter: alpha

server:
  servlet:
    encoding:
      force-response: true # 한글 인코딩 반환 강제화

storage:
  imgbb:
    api-key: ${IMGBB_API_KEY:your-api-key}
